// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8-9bAijUOeuYfvU393lK3GeU770313OY',
    appId: '1:211693755202:web:ab5189811dccec358706db',
    messagingSenderId: '211693755202',
    projectId: 'message-board-93c60',
    authDomain: 'message-board-93c60.firebaseapp.com',
    storageBucket: 'message-board-93c60.firebasestorage.app',
    measurementId: 'G-76JV7FS5M6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXyXjoevqXF8DW1MERgsl5aYLpICJu7-I',
    appId: '1:211693755202:android:637dd93dfd3e30b98706db',
    messagingSenderId: '211693755202',
    projectId: 'message-board-93c60',
    storageBucket: 'message-board-93c60.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQYKzFPi8MkMBcwwKfeDr-h9-AmijyfXg',
    appId: '1:211693755202:ios:858f5595d250d05a8706db',
    messagingSenderId: '211693755202',
    projectId: 'message-board-93c60',
    storageBucket: 'message-board-93c60.firebasestorage.app',
    iosBundleId: 'com.example.messageBoard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQYKzFPi8MkMBcwwKfeDr-h9-AmijyfXg',
    appId: '1:211693755202:ios:858f5595d250d05a8706db',
    messagingSenderId: '211693755202',
    projectId: 'message-board-93c60',
    storageBucket: 'message-board-93c60.firebasestorage.app',
    iosBundleId: 'com.example.messageBoard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8-9bAijUOeuYfvU393lK3GeU770313OY',
    appId: '1:211693755202:web:a797aea64343be0a8706db',
    messagingSenderId: '211693755202',
    projectId: 'message-board-93c60',
    authDomain: 'message-board-93c60.firebaseapp.com',
    storageBucket: 'message-board-93c60.firebasestorage.app',
    measurementId: 'G-PZG6VDNC3H',
  );
}
